version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./files/load_data.sql:/docker-entrypoint-initdb.d/load_data.sql
      - ./files/credit_risk_dataset.csv:/tmp/credit_risk_dataset.csv
    environment:
      POSTGRES_USER: useralvin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: dbalvin
    # restart: unless-stopped
    ports:
      - "5433:5432"